# Generated by Django 6.0.1 on 2026-08-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The primary key of the model instance')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON data storing agent memory/state')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='The type of model this memory is attached to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Agent Memory',
                'verbose_name_plural': 'Agent Memories',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='django_mode_content_27e3bd_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
